# Configuration for lintrunner https://github.com/suo/lintrunner
# You can install the dependencies and initialize with
#
# ```sh
# pip install lintrunner lintrunner-adapters
# lintrunner init
# ```
#
# This will install lintrunner on your system and download all the necessary
# dependencies to run linters locally.
# If you want to see what lintrunner init will install, run
# `lintrunner init --dry-run`.
#
# To lint local changes:
#
# ```bash
# lintrunner -m main
# ```
#
# To lint all files:
#
# ```bash
# lintrunner --all-files
# ```
#
# To format files:
#
# ```bash
# lintrunner f --all-files
# ```
#
# To read more about lintrunner, see [wiki](https://github.com/pytorch/pytorch/wiki/lintrunner).
# To update an existing linting rule or create a new one, modify this file or create a
# new adapter following examples in https://github.com/justinchuby/lintrunner-adapters.

[[linter]]
code = 'FLAKE8'
include_patterns = [
    '**/*.py',
]
exclude_patterns = [
    'build/**',
    'cmake/external/**',
    # TODO enable
    'docs/python/**',
    # ignore generated flatbuffers code
    'onnxruntime/core/flatbuffers/ort_flatbuffers_py/**',
    # TODO enable
    './onnxruntime/python/tools/**',
    # FIXME(#7032): ignore test code for now
    'onnxruntime/test/**',
    # TODO enable
    'orttraining/**',
    # FIXME: DUO106
    'tools/nuget/generate_nuspec_for_native_nuget.py',
    # FIXME: DUO116
    'js/scripts/build_web.py',
    # FIXME: Too many errors
    'onnxruntime/python/tools/tensorrt/perf/**',
]
command = [
    'python3',
    '-m',
    'lintrunner_adapters',
    'run',
    'flake8_linter',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python3',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'flake8==5.0.4',
    'flake8-bugbear==22.10.27',
    'flake8-pyi==22.10.0',
    'dlint==0.13.0',
]

[[linter]]
code = 'BLACK-ISORT'
include_patterns = [
    '**/*.py',
]
exclude_patterns = [
    'cmake/**',
    'orttraining/*',
    'onnxruntime/core/flatbuffers/**',
]
command = [
    'python3',
    '-m',
    'lintrunner_adapters',
    'run',
    'black_isort_linter',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python3',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'black==22.10.0',
    'isort==5.10.1',
]
is_formatter = true

[[linter]]
code = 'PYLINT'
include_patterns = [
    # TODO: Opt in to pylint by adding paths here
]
exclude_patterns = [
]
command = [
    'python3',
    '-m',
    'lintrunner_adapters',
    'run',
    'pylint_linter',
    '--rcfile=pyproject.toml',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python3',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'pylint==2.15.5',
]
